package com.jcurcio.rorc.bevcart;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

import com.firebase.client.Firebase;

import org.w3c.dom.Text;

import java.util.HashMap;
import java.util.Map;

public class OrderScreen extends AppCompatActivity {

    Button placeOrder;
    TextView beerNum;
    TextView hotdogNum;
    TextView burgerNum;
    TextView chipsNum;
    TextView holeNum;

    Firebase ref = new Firebase("https://bevcart.firebaseio.com");

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_order_screen);

        placeOrder = (Button) findViewById(R.id.placeOrder);
        beerNum = (TextView) findViewById(R.id.beerNum);
        hotdogNum = (TextView) findViewById(R.id.hotdogNum);
        chipsNum = (TextView) findViewById(R.id.chipsNum);
        holeNum = (TextView) findViewById(R.id.chipsNum);

        placeOrder.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Firebase postOrderRef = ref.child("orders");
                Firebase postOrder = postOrderRef.push();
                // Add some data to the new location
                Map<String, String> newOrder = new HashMap<String, String>();
                newOrder.put("beer:", beerNum.getText().toString());
                newOrder.put("burger", burgerNum.getText().toString());
                newOrder.put("chips", chipsNum.getText().toString());
                newOrder.put("complete", "false");
                newOrder.put("hole", holeNum.getText().toString());
                newOrder.put("hotdog", hotdogNum.getText().toString());
                newOrder.put("provider", "n/a");
                newOrder.put("price", "40000");
                newOrder.put("user", ref.getAuth().getUid().toString());

                postOrder.setValue(newOrder);
                // Get the unique ID generated by push()
                String postId = postOrder.getKey();

                startActivity(new Intent(OrderScreen.this, user_home.class));

            }
        });
    }
}
